### ISSUE TITLE
Xcode 7 

### ISSUE THREAD

**Issue by jidedao** [danoli3/ofxiOSBoost#24] opened 2015-10-09 01:55 UTC
I find some error issues when running my project on xcode 7 iOS simulator. Error tip is "building for iOS simulator, but linking in object file built for OSX, for architecture x86_64"

**Comment by danoli3** [comment] 2015-10-09 03:04
Have you updated to the latest 1.59.0?

**Comment by jidedao** [comment] 2015-10-09 03:08
I'm sorry,I downloaded some days ago.I'm trying again

**Comment by danoli3** [comment] 2015-10-09 03:09
Yeah the old version had this issue. Definitely fixed with the 1.59.0 release

**Comment by jidedao** [comment] 2015-10-09 03:30
I has some new issues When running iOS simulator that is iphone6。“Undefined symbols for architecture x86_64:
  "std::string::find_last_of(char const*, unsigned long, unsigned long) const", referenced from:
      boost::filesystem::path::m_parent_path_end() const in boost.a(path.o)
      boost::filesystem::path::filename() const in boost.a(path.o)
      boost::filesystem::path::m_path_iterator_decrement(boost::filesystem::path::iterator&) in boost.a(path.o)
  "std::string::find_first_of(char const*, unsigned long, unsigned long) const", referenced from:
      boost::filesystem::path::m_parent_path_end() const in boost.a(path.o)
      boost::filesystem::path::root_path() const in boost.a(path.o)
      boost::filesystem::path::root_directory() const in boost.a(path.o)
      boost::filesystem::path::filename() const in boost.a(path.o)
      boost::filesystem::path::m_normalize() in boost.a(path.o)
      boost::filesystem::path::m_path_iterator_increment(boost::filesystem::path::iterator&) in boost.a(path.o)
      boost::filesystem::path::m_path_iterator_decrement(boost::filesystem::path::iterator&) in boost.a(path.o)
      ...
  "std::string::rfind(char, unsigned long) const", referenced from:
      boost::filesystem::path::extension() const in boost.a(path.o)
      boost::filesystem::path::stem() const in boost.a(path.o)
  "std::string::compare(char const*) const", referenced from:
      boost::gregorian::special_value_from_string(std::string const&) in boost.a(greg_month.o)
      boost::filesystem::path::begin() const in boost.a(path.o)
      boost::filesystem::path::m_path_iterator_decrement(boost::filesystem::path::iterator&) in boost.a(path.o)
  "std::locale::id::_M_id() const", referenced from:
      boost::filesystem::path::codecvt() in boost.a(path.o)
  "std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::_M_leak_hard()", referenced from:
      boost::date_time::date_names_put<boost::gregorian::greg_facet_config, wchar_t, std::ostreambuf_iterator<wchar_t, std::char_traits<wchar_t> > >::put_string(std::ostreambuf_iterator<wchar_t, std::char_traits<wchar_t> >&, wchar_t const*) const in boost.a(greg_month.o)
  "std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::_Rep::_M_destroy(std::allocator<wchar_t> const&)", referenced from:
      boost::date_time::date_names_put<boost::gregorian::greg_facet_config, wchar_t, std::ostreambuf_iterator<wchar_t, std::char_traits<wchar_t> > >::do_year_sep_char(std::ostreambuf_iterator<wchar_t, std::char_traits<wchar_t> >&) const in boost.a(greg_month.o)
      boost::date_time::date_names_put<boost::gregorian::greg_facet_config, wchar_t, std::ostreambuf_iterator<wchar_t, std::char_traits<wchar_t> > >::put_string(std::ostreambuf_iterator<wchar_t, std::char_traits<wchar_t> >&, wchar_t const*) const in boost.a(greg_month.o)
  "std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::_Rep::_S_empty_rep_storage", referenced from:
      boost::date_time::date_names_put<boost::gregorian::greg_facet_config, wchar_t, std::ostreambuf_iterator<wchar_t, std::char_traits<wchar_t> > >::do_year_sep_char(std::ostreambuf_iterator<wchar_t, std::char_traits<wchar_t> >&) const in boost.a(greg_month.o)
      boost::date_time::date_names_put<boost::gregorian::greg_facet_config, wchar_t, std::ostreambuf_iterator<wchar_t, std::char_traits<wchar_t> > >::put_string(std::ostreambuf_iterator<wchar_t, std::char_traits<wchar_t> >&, wchar_t const*) const in boost.a(greg_month.o)
  "std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::assign(wchar_t const*, unsigned long)", referenced from:
      boost::date_time::date_names_put<boost::gregorian::greg_facet_config, wchar_t, std::ostreambuf_iterator<wchar_t, std::char_traits<wchar_t> > >::put_string(std::ostreambuf_iterator<wchar_t, std::char_traits<wchar_t> >&, wchar_t const*) const in boost.a(greg_month.o)
  "std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::basic_string(wchar_t const*, std::allocator<wchar_t> const&)", referenced from:
      boost::date_time::date_names_put<boost::gregorian::greg_facet_config, wchar_t, std::ostreambuf_iterator<wchar_t, std::char_traits<wchar_t> > >::do_year_sep_char(std::ostreambuf_iterator<wchar_t, std::char_traits<wchar_t> >&) const in boost.a(greg_month.o)
  "std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::basic_string(std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&)", referenced from:
      boost::date_time::date_names_put<boost::gregorian::greg_facet_config, wchar_t, std::ostreambuf_iterator<wchar_t, std::char_traits<wchar_t> > >::put_string(std::ostreambuf_iterator<wchar_t, std::char_traits<wchar_t> >&, wchar_t const*) const in boost.a(greg_month.o)
  "std::string::_M_leak_hard()", referenced from:
      boost::filesystem::detail::directory_iterator_construct(boost::filesystem::directory_iterator&, boost::filesystem::path const&, boost::system::error_code*) in boost.a(operations.o)
      boost::filesystem::detail::directory_iterator_increment(boost::filesystem::directory_iterator&, boost::system::error_code*) in boost.a(operations.o)
      boost::gregorian::greg_month::get_month_map_ptr() in boost.a(greg_month.o)
      boost::date_time::date_names_put<boost::gregorian::greg_facet_config, char, std::ostreambuf_iterator<char, std::char_traits<char> > >::put_string(std::ostreambuf_iterator<char, std::char_traits<char> >&, char const*) const in boost.a(greg_month.o)
      boost::filesystem::path::operator/=(boost::filesystem::path const&) in boost.a(path.o)
      boost::filesystem::path::m_append_separator_if_needed() in boost.a(path.o)
      boost::filesystem::path::operator/=(char const*) in boost.a(path.o)
      ...
  "std::string::_M_replace_aux(unsigned long, unsigned long, unsigned long, char)", referenced from:
      boost::filesystem::path::m_path_iterator_increment(boost::filesystem::path::iterator&) in boost.a(path.o)
  "std::string::_Rep::_M_destroy(std::allocator<char> const&)", referenced from:
      boost::filesystem::absolute(boost::filesystem::path const&, boost::filesystem::path const&) in boost.a(operations.o)
      boost::filesystem::detail::canonical(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*) in boost.a(operations.o)
      boost::filesystem::detail::symlink_status(boost::filesystem::path const&, boost::system::error_code*) in boost.a(operations.o)
      boost::filesystem::detail::read_symlink(boost::filesystem::path const&, boost::system::error_code*) in boost.a(operations.o)
      boost::filesystem::detail::copy(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*) in boost.a(operations.o)
      boost::filesystem::detail::copy_directory(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*) in boost.a(operations.o)
      boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::detail::copy_option, boost::system::error_code*) in boost.a(operations.o)
      ...
  "std::string::_Rep::_S_terminal", referenced from:
      boost::filesystem::path& boost::filesystem::path::assign<char*>(char*, char*) in boost.a(operations.o)
      boost::filesystem::path::operator/=(boost::filesystem::path const&) in boost.a(path.o)
      boost::filesystem::path::m_append_separator_if_needed() in boost.a(path.o)
      boost::filesystem::path::operator/=(char const*) in boost.a(path.o)
      boost::filesystem::path::replace_extension(boost::filesystem::path const&) in boost.a(path.o)
      boost::filesystem::path::path<char const*>(char const*, char const*) in boost.a(path.o)
  "std::string::_Rep::_S_empty_rep_storage", referenced from:
      boost::filesystem::absolute(boost::filesystem::path const&, boost::filesystem::path const&) in boost.a(operations.o)
      boost::filesystem::detail::canonical(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*) in boost.a(operations.o)
      boost::filesystem::detail::symlink_status(boost::filesystem::path const&, boost::system::error_code*) in boost.a(operations.o)
      boost::filesystem::detail::read_symlink(boost::filesystem::path const&, boost::system::error_code*) in boost.a(operations.o)
      boost::filesystem::detail::copy(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*) in boost.a(operations.o)
      boost::filesystem::detail::copy_directory(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*) in boost.a(operations.o)
      boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::detail::copy_option, boost::system::error_code*) in boost.a(operations.o)
      ...
  "std::string::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&)", referenced from:
      boost::filesystem::path& boost::filesystem::path::assign<char*>(char*, char*) in boost.a(operations.o)
      boost::filesystem::path::path<char const*>(char const*, char const*) in boost.a(path.o)
  "std::string::append(char const*, unsigned long)", referenced from:
      boost::system::system_error::what() const in boost.a(operations.o)
      boost::filesystem::filesystem_error::what() const in boost.a(operations.o)
      boost::filesystem::path::operator/=(char const*) in boost.a(path.o)
      boost::filesystem::path::root_path() const in boost.a(path.o)
  "std::string::append(std::string const&)", referenced from:
      boost::system::system_error::what() const in boost.a(operations.o)
      boost::filesystem::filesystem_error::what() const in boost.a(operations.o)
      boost::filesystem::path::operator/=(boost::filesystem::path const&) in boost.a(path.o)
      boost::filesystem::path::operator/=(char const*) in boost.a(path.o)
      boost::filesystem::path::replace_extension(boost::filesystem::path const&) in boost.a(path.o)
  "std::string::assign(char const*, unsigned long)", referenced from:
      boost::filesystem::detail::current_path(boost::system::error_code*) in boost.a(operations.o)
      boost::filesystem::detail::directory_iterator_increment(boost::filesystem::directory_iterator&, boost::system::error_code*) in boost.a(operations.o)
      boost::system::system_error::what() const in boost.a(operations.o)
      boost::filesystem::filesystem_error::what() const in boost.a(operations.o)
      boost::gregorian::greg_month::get_month_map_ptr() in boost.a(greg_month.o)
      boost::date_time::date_names_put<boost::gregorian::greg_facet_config, char, std::ostreambuf_iterator<char, std::char_traits<char> > >::put_string(std::ostreambuf_iterator<char, std::char_traits<char> >&, char const*) const in boost.a(greg_month.o)
      boost::filesystem::path::begin() const in boost.a(path.o)
      ...
  "std::string::assign(std::string const&)", referenced from:
      boost::filesystem::detail::canonical(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*) in boost.a(operations.o)
      boost::filesystem::detail::initial_path(boost::system::error_code*) in boost.a(operations.o)
      boost::filesystem::path_traits::dispatch(boost::filesystem::directory_entry const&, std::string&, std::codecvt<wchar_t, char, __mbstate_t> const&) in boost.a(operations.o)
      boost::filesystem::path_traits::dispatch(boost::filesystem::directory_entry const&, std::string&) in boost.a(operations.o)
      boost::filesystem::detail::directory_iterator_construct(boost::filesystem::directory_iterator&, boost::filesystem::path const&, boost::system::error_code*) in boost.a(operations.o)
      boost::filesystem::filesystem_error::filesystem_error(std::string const&, boost::filesystem::path const&, boost::system::error_code) in boost.a(operations.o)
      boost::filesystem::filesystem_error::filesystem_error(std::string const&, boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code) in boost.a(operations.o)
      ...
  "std::string::replace(unsigned long, unsigned long, char const*, unsigned long)", referenced from:
      boost::filesystem::path& boost::filesystem::path::assign<char*>(char*, char*) in boost.a(operations.o)
      boost::filesystem::path::path<char const*>(char const*, char const*) in boost.a(path.o)
  "std::string::reserve(unsigned long)", referenced from:
      boost::filesystem::path::operator/=(boost::filesystem::path const&) in boost.a(path.o)
      boost::filesystem::path::m_append_separator_if_needed() in boost.a(path.o)
      boost::filesystem::path::operator/=(char const*) in boost.a(path.o)
      boost::filesystem::path::replace_extension(boost::filesystem::path const&) in boost.a(path.o)
  "std::string::_M_mutate(unsigned long, unsigned long, unsigned long)", referenced from:
      boost::filesystem::detail::canonical(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*) in boost.a(operations.o)
      boost::filesystem::path& boost::filesystem::path::assign<char*>(char*, char*) in boost.a(operations.o)
      boost::filesystem::path::m_erase_redundant_separator(unsigned long) in boost.a(path.o)
      boost::filesystem::path::remove_filename() in boost.a(path.o)
      boost::filesystem::path::remove_trailing_separator() in boost.a(path.o)
      boost::filesystem::path::replace_extension(boost::filesystem::path const&) in boost.a(path.o)
      boost::filesystem::path::m_normalize() in boost.a(path.o)
      ...
  "std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)", referenced from:
      boost::filesystem::detail::canonical(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*) in boost.a(operations.o)
      boost::filesystem::detail::symlink_status(boost::filesystem::path const&, boost::system::error_code*) in boost.a(operations.o)
      boost::filesystem::detail::read_symlink(boost::filesystem::path const&, boost::system::error_code*) in boost.a(operations.o)
      boost::filesystem::detail::copy(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*) in boost.a(operations.o)
      boost::filesystem::detail::copy_directory(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*) in boost.a(operations.o)
      boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::detail::copy_option, boost::system::error_code*) in boost.a(operations.o)
      boost::filesystem::detail::create_symlink(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*) in boost.a(operations.o)
      ...
  "std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&)", referenced from:
      boost::filesystem::absolute(boost::filesystem::path const&, boost::filesystem::path const&) in boost.a(operations.o)
      boost::filesystem::detail::canonical(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*) in boost.a(operations.o)
      boost::filesystem::detail::initial_path(boost::system::error_code*) in boost.a(operations.o)
      boost::filesystem::detail::system_complete(boost::filesystem::path const&, boost::system::error_code*) in boost.a(operations.o)
      boost::filesystem::detail::directory_iterator_construct(boost::filesystem::directory_iterator&, boost::filesystem::path const&, boost::system::error_code*) in boost.a(operations.o)
      boost::filesystem::detail::directory_iterator_increment(boost::filesystem::directory_iterator&, boost::system::error_code*) in boost.a(operations.o)
      boost::gregorian::greg_month::get_month_map_ptr() in boost.a(greg_month.o)
      ...
  "std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&, unsigned long, unsigned long)", referenced from:
      boost::filesystem::path::begin() const in boost.a(path.o)
      boost::filesystem::path::m_path_iterator_increment(boost::filesystem::path::iterator&) in boost.a(path.o)
      boost::filesystem::path::m_path_iterator_decrement(boost::filesystem::path::iterator&) in boost.a(path.o)
  "std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()", referenced from:
      boost::system::(anonymous namespace)::generic_error_category::message(int) const in boost.a(error_code.o)
  "std::out_of_range::out_of_range(std::string const&)", referenced from:
      boost::gregorian::bad_month::bad_month() in boost.a(greg_month.o)
  "std::runtime_error::runtime_error(std::string const&)", referenced from:
      boost::filesystem::filesystem_error::filesystem_error(std::string const&, boost::filesystem::path const&, boost::system::error_code) in boost.a(operations.o)
      boost::filesystem::filesystem_error::filesystem_error(std::string const&, boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code) in boost.a(operations.o)
      boost::filesystem::filesystem_error::filesystem_error(std::string const&, boost::system::error_code) in boost.a(operations.o)
  "std::locale::_Impl::_M_install_facet(std::locale::id const*, std::locale::facet const*)", referenced from:
      std::locale::locale<boost::date_time::all_date_names_put<boost::gregorian::greg_facet_config, char, std::ostreambuf_iterator<char, std::char_traits<char> > > >(std::locale const&, boost::date_time::all_date_names_put<boost::gregorian::greg_facet_config, char, std::ostreambuf_iterator<char, std::char_traits<char> > >*) in boost.a(greg_month.o)
      std::locale::locale<boost::date_time::all_date_names_put<boost::gregorian::greg_facet_config, wchar_t, std::ostreambuf_iterator<wchar_t, std::char_traits<wchar_t> > > >(std::locale const&, boost::date_time::all_date_names_put<boost::gregorian::greg_facet_config, wchar_t, std::ostreambuf_iterator<wchar_t, std::char_traits<wchar_t> > >*) in boost.a(greg_month.o)
      std::locale::locale<boost::filesystem::detail::utf8_codecvt_facet>(std::locale const&, boost::filesystem::detail::utf8_codecvt_facet*) in boost.a(path.o)
  "std::locale::_Impl::_Impl(std::locale::_Impl const&, unsigned long)", referenced from:
      std::locale::locale<boost::date_time::all_date_names_put<boost::gregorian::greg_facet_config, char, std::ostreambuf_iterator<char, std::char_traits<char> > > >(std::locale const&, boost::date_time::all_date_names_put<boost::gregorian::greg_facet_config, char, std::ostreambuf_iterator<char, std::char_traits<char> > >*) in boost.a(greg_month.o)
      std::locale::locale<boost::date_time::all_date_names_put<boost::gregorian::greg_facet_config, wchar_t, std::ostreambuf_iterator<wchar_t, std::char_traits<wchar_t> > > >(std::locale const&, boost::date_time::all_date_names_put<boost::gregorian::greg_facet_config, wchar_t, std::ostreambuf_iterator<wchar_t, std::char_traits<wchar_t> > >*) in boost.a(greg_month.o)
      std::locale::locale<boost::filesystem::detail::utf8_codecvt_facet>(std::locale const&, boost::filesystem::detail::utf8_codecvt_facet*) in boost.a(path.o)
  "std::locale::_Impl::~_Impl()", referenced from:
      std::locale::locale<boost::date_time::all_date_names_put<boost::gregorian::greg_facet_config, char, std::ostreambuf_iterator<char, std::char_traits<char> > > >(std::locale const&, boost::date_time::all_date_names_put<boost::gregorian::greg_facet_config, char, std::ostreambuf_iterator<char, std::char_traits<char> > >*) in boost.a(greg_month.o)
      std::locale::locale<boost::date_time::all_date_names_put<boost::gregorian::greg_facet_config, wchar_t, std::ostreambuf_iterator<wchar_t, std::char_traits<wchar_t> > > >(std::locale const&, boost::date_time::all_date_names_put<boost::gregorian::greg_facet_config, wchar_t, std::ostreambuf_iterator<wchar_t, std::char_traits<wchar_t> > >*) in boost.a(greg_month.o)
      std::locale::locale<boost::filesystem::detail::utf8_codecvt_facet>(std::locale const&, boost::filesystem::detail::utf8_codecvt_facet*) in boost.a(path.o)
  "std::locale::facet::~facet()", referenced from:
      boost::date_time::all_date_names_put<boost::gregorian::greg_facet_config, char, std::ostreambuf_iterator<char, std::char_traits<char> > >::~all_date_names_put() in boost.a(greg_month.o)
      boost::date_time::all_date_names_put<boost::gregorian::greg_facet_config, char, std::ostreambuf_iterator<char, std::char_traits<char> > >::~all_date_names_put() in boost.a(greg_month.o)
      boost::date_time::all_date_names_put<boost::gregorian::greg_facet_config, wchar_t, std::ostreambuf_iterator<wchar_t, std::char_traits<wchar_t> > >::~all_date_names_put() in boost.a(greg_month.o)
      boost::date_time::all_date_names_put<boost::gregorian::greg_facet_config, wchar_t, std::ostreambuf_iterator<wchar_t, std::char_traits<wchar_t> > >::~all_date_names_put() in boost.a(greg_month.o)
  "std::locale::classic()", referenced from:
      boost::gregorian::greg_month::get_month_map_ptr() in boost.a(greg_month.o)
  "std::locale::locale(std::locale const&)", referenced from:
      boost::gregorian::greg_month::get_month_map_ptr() in boost.a(greg_month.o)
      boost::filesystem::path::imbue(std::locale const&) in boost.a(path.o)
  "std::locale::locale()", referenced from:
      boost::filesystem::path::codecvt() in boost.a(path.o)
      boost::filesystem::path::imbue(std::locale const&) in boost.a(path.o)
  "std::locale::~locale()", referenced from:
      boost::gregorian::greg_month::get_month_map_ptr() in boost.a(greg_month.o)
      boost::filesystem::path::codecvt() in boost.a(path.o)
      boost::filesystem::path::imbue(std::locale const&) in boost.a(path.o)
  "std::locale::operator=(std::locale const&)", referenced from:
      boost::filesystem::path::imbue(std::locale const&) in boost.a(path.o)
  "std::codecvt<wchar_t, char, __mbstate_t>::id", referenced from:
      boost::filesystem::path::codecvt() in boost.a(path.o)
      std::locale::locale<boost::filesystem::detail::utf8_codecvt_facet>(std::locale const&, boost::filesystem::detail::utf8_codecvt_facet*) in boost.a(path.o)
  "std::codecvt<wchar_t, char, __mbstate_t>::codecvt(unsigned long)", referenced from:
      boost::filesystem::path::codecvt() in boost.a(path.o)
      boost::filesystem::path::imbue(std::locale const&) in boost.a(path.o)
  "std::codecvt<wchar_t, char, __mbstate_t>::~codecvt()", referenced from:
      boost::filesystem::detail::utf8_codecvt_facet::~utf8_codecvt_facet() in boost.a(utf8_codecvt_facet.o)
      boost::filesystem::detail::utf8_codecvt_facet::~utf8_codecvt_facet() in boost.a(utf8_codecvt_facet.o)
  "std::ios_base::Init::Init()", referenced from:
      __GLOBAL__sub_I_greg_month.cpp in boost.a(greg_month.o)
  "std::ios_base::Init::~Init()", referenced from:
      __GLOBAL__sub_I_greg_month.cpp in boost.a(greg_month.o)
  "std::__throw_bad_cast()", referenced from:
      boost::filesystem::path::codecvt() in boost.a(path.o)
  "std::_Rb_tree_decrement(std::_Rb_tree_node_base*)", referenced from:
      std::_Rb_tree<std::string, std::pair<std::string const, unsigned short>, std::_Select1st<std::pair<std::string const, unsigned short> >, std::less<std::string>, std::allocator<std::pair<std::string const, unsigned short> > >::_M_insert_unique(std::pair<std::string const, unsigned short> const&) in boost.a(greg_month.o)
  "std::__throw_logic_error(char const*)", referenced from:
      boost::filesystem::path& boost::filesystem::path::assign<char*>(char*, char*) in boost.a(operations.o)
      boost::filesystem::path::path<char const*>(char const*, char const*) in boost.a(path.o)
  "std::__throw_out_of_range(char const*)", referenced from:
      boost::filesystem::path::begin() const in boost.a(path.o)
      boost::filesystem::path::m_erase_redundant_separator(unsigned long) in boost.a(path.o)
      boost::filesystem::path::remove_filename() in boost.a(path.o)
      boost::filesystem::path::remove_trailing_separator() in boost.a(path.o)
      boost::filesystem::path::replace_extension(boost::filesystem::path const&) in boost.a(path.o)
      boost::filesystem::path::m_normalize() in boost.a(path.o)
      boost::filesystem::path::m_path_iterator_increment(boost::filesystem::path::iterator&) in boost.a(path.o)
      ...
  "std::_Rb_tree_insert_and_rebalance(bool, std::_Rb_tree_node_base*, std::_Rb_tree_node_base*, std::_Rb_tree_node_base&)", referenced from:
      std::_Rb_tree<std::string, std::pair<std::string const, unsigned short>, std::_Select1st<std::pair<std::string const, unsigned short> >, std::less<std::string>, std::allocator<std::pair<std::string const, unsigned short> > >::_M_insert(std::_Rb_tree_node_base*, std::_Rb_tree_node_base*, std::pair<std::string const, unsigned short> const&) in boost.a(greg_month.o)
  "std::ctype<char> const& std::use_facet<std::ctype<char> >(std::locale const&)", referenced from:
      boost::gregorian::greg_month::get_month_map_ptr() in boost.a(greg_month.o)
  "typeinfo for std::locale::facet", referenced from:
      typeinfo for boost::date_time::date_names_put<boost::gregorian::greg_facet_config, char, std::ostreambuf_iterator<char, std::char_traits<char> > > in boost.a(greg_month.o)
      typeinfo for boost::date_time::date_names_put<boost::gregorian::greg_facet_config, wchar_t, std::ostreambuf_iterator<wchar_t, std::char_traits<wchar_t> > > in boost.a(greg_month.o)
  "typeinfo for std::codecvt<wchar_t, char, __mbstate_t>", referenced from:”

**Comment by danoli3** [comment] 2015-10-09 04:03
String Issues are usually caused by mixing C++11 / libc++ with C++98. 
Make sure you have the project set to Libc++ or download the other tag for libstdc++ if you need c++98 (libstdc++)

**Comment by danoli3** [comment] 2015-10-09 04:04
I.E:

> You have to change your project or target build settings.

> Under Apple LLVM 6.0 - Language - C++ make the following changes

> C++ Language Dialect to C++11 [-std=c++11] C++ Standard Library to libc++ (LLVM C++ standard library with C++11 support)

**Comment by jidedao** [comment] 2015-10-09 05:05
![09c86524-f9dc-4857-97a0-95bee8600087](https://cloud.githubusercontent.com/assets/7794454/10386156/ba20f504-6e85-11e5-943b-dfa99e02a9f1.png)
My project build settings is so

**Comment by danoli3** [comment] 2015-10-09 05:23
Have you checked out master? Or which tag did you download?

**Comment by jidedao** [comment] 2015-10-09 05:25
I click the downloaded url

**Comment by jidedao** [comment] 2015-10-09 05:26
and run the file "build-libstdc++.sh"

**Comment by jidedao** [comment] 2015-10-09 05:30
I find the case that i forget import "libstdc++.tbd" and "libstdc++.6.tbd"

**Comment by jidedao** [comment] 2015-10-09 05:30
thanks

**Comment by danoli3** [comment] 2015-10-09 05:47
Hmmm, You are Using Libc++ and building build-libstdc++.sh.

You should be using build-libc++.sh

Importing libstdc++ is just a "hack" for the real issue you are using the wrong libs. :D!

**Comment by danoli3** [comment] 2015-10-09 05:48
Try and rebuild with ```build-libc++.sh```, remove your libstdc++ imports.

**Comment by jidedao** [comment] 2015-10-09 05:51
ok,I try again

**Comment by jidedao** [comment] 2015-10-09 06:04
ok， it's seem work fine.Thank you very much.

**Closed** 2015-10-09 06:13 UTC
